# Generated by Django 5.0.1 on 2024-03-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
