# Generated by Django 5.0.1 on 2024-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_userregister_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('package_type', models.CharField(max_length=50)),
                ('package_location', models.CharField(max_length=100)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_features', models.TextField()),
                ('package_details', models.TextField()),
                ('package_image', models.ImageField(upload_to='package_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='userregister',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
    ]
