# Generated by Django 5.0.1 on 2024-03-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRaised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tour_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
    ]
