# Generated by Django 5.0.1 on 2024-03-29 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_ticketraised'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.createpackage')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.userregister')),
            ],
        ),
    ]
